version: 2

sources:
  - name: ecommerce              # logical name for source
    database: raw
    schema: ECOMMERCE
    tables:
      - name: raw_customers
      - name: raw_orders

  - name: rawsource              # logical name for source
    database: demo_db
    schema: public
    tables:
      - name: raw_customers
      - name: raw_orders    

models:
  - name: Gen_Tst_customers
    description: "Customer master table"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: country
        tests:
          - accepted_values:
              values: ['US', 'CA', 'IN', 'UK', 'AU', 'KR', 'RU']

  - name: Gen_Tst_orders
    description: "Customer orders"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: id
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'shipped', 'completed']
