version: 2

sources:
  - name: ecommerce              # logical name for source
    database: raw
    schema: ECOMMERCE
    tables:
      - name: raw_customers
      - name: raw_orders

  - name: rawsource              # logical name for source
    database: demo_db
    schema: public
    tables:
      - name: raw_customers
      - name: raw_orders    

  - name: Sourcedemo                # Day4_2TestonSourceTbl Source name is Sourcedemo
    database: DEMO_DB
    schema: public
    tables:
      - name: Tst_Sr_Tbl_CUSTOMERS  # Day4_2TestonSourceTbl Tst_Sr_Tbl_CUSTOMERS
        description: Demo customers
        columns:
          - name: CUST_ID
            tests:
              - not_null
              - unique
          - name: EMAIL
            tests:
              - not_null
      - name: Tst_Sr_Tbl_ORDERS     # Day4_2TestonSourceTbl Tst_Sr_Tbl_ORDERS
        description: Demo orders
        columns:
          - name: ORDER_ID
            tests: [not_null, unique]
          - name: STATUS
            tests:
              - not_null
              - accepted_values:
                  values: ['O','F','P']
          - name: CUST_ID
            tests:
              - not_null
              - relationships:
                  to: source('Sourcedemo','Tst_Sr_Tbl_CUSTOMERS')
                  field: CUST_ID

  - name: demoSr_Tbl_Mdl            # Day4_3TestonSourceTblModels Tst_Sr_Tbl_Mdl_orders_raw
    database: DEMO_DB
    schema: public
    tables:
      - name: Tst_Sr_Tbl_Mdl_orders_raw
        description: Demo orders
        columns:
          - name: ORDER_ID
            tests: [not_null, unique]
          - name: STATUS
            tests:
              - not_null
              - accepted_values:
                  values: ['shipped', 'completed', 'pending']
  
  - name: demo_Tst_store_failures   # Day4_6Tst_store_failures
    database: DEMO_DB
    schema: public
    tables:
      - name: Tst_store_failures_orders_raw
        description: Demo orders (raw from source system)
        columns:
          - name: ORDER_ID
            tests:
              - not_null:
                  severity: error           # fail pipeline in CI/CD if nulls
                  store_failures: true      # persist bad rows
              - unique:
                  severity: error
                  store_failures: true
          - name: STATUS
            tests:
              - not_null:
                  severity: error
                  store_failures: true
              - accepted_values:
                  values: ['shipped', 'completed', 'pending']
                  severity: warn            # warn only, don’t block
                  store_failures: true



models:     
  - name: Gen_Tst_customers_M       # Day4_1GenTst Model name Gen_Tst_customers_M
    description: "Customer master table"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: country
        tests:
          - accepted_values:
              values: ['US', 'CA', 'IN', 'UK', 'AU', 'KR', 'RU']

  - name: Gen_Tst_orders_M
    description: "Customer orders"    # Day4_1GenTst Model name Gen_Tst_orders_M
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: id
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'shipped', 'completed']

              
  - name: Tst_Mdl_orders_raw
    description: "Staging orders table (built from demo.orders_raw)"
    columns:
      - name: ORDER_ID
        tests:
          - not_null
          - unique
      - name: STATUS
        tests:
          - not_null
          - accepted_values:
              values: ['shipped', 'completed', 'pending']